package unifi

import (
	"fmt"
)

func (u *Unifi) GetWLANs(site *Site) ([]*WLAN, error) {
	data := make([]*WLAN, 0)

	var response struct {
		Data []*WLAN `json:"data"`
	}

	u.DebugLog("Polling Controller, retreiving UniFi WLANs, site %s ", site.SiteName)

	wlanPath := fmt.Sprintf(APIWLANPath, site.Name)
	if err := u.GetData(wlanPath, &response); err != nil {
		return nil, err
	}

	data = append(data, response.Data...)

	return data, nil
}

func (u *Unifi) SetWLANPassword(siteName string, password string, wlan *WLAN) (bool, error) {
	var response struct {
		Data []*WLAN `json:"data"`
	}

	wlanPath := fmt.Sprintf(APIWLANPath+"/%s", siteName, wlan.Id)
	payload := fmt.Sprintf(`{"x_passphrase":"%s"}`, password)

	if err := u.PutData(wlanPath, &response, payload); err != nil {
		return false, err
	}

	return true, nil
}

type WLAN struct {
	SettingPreference           string        `json:"setting_preference"`
	Dtim6E                      int           `json:"dtim_6e"`
	Wpa3Support                 bool          `json:"wpa3_support"`
	MinrateNaAdvertisingRates   bool          `json:"minrate_na_advertising_rates"`
	WpaMode                     string        `json:"wpa_mode"`
	MinrateSettingPreference    string        `json:"minrate_setting_preference"`
	MinrateNgAdvertisingRates   bool          `json:"minrate_ng_advertising_rates"`
	RadiusDasEnabled            bool          `json:"radius_das_enabled"`
	GroupRekey                  int           `json:"group_rekey"`
	RadiusMacaclFormat          string        `json:"radius_macacl_format"`
	PmfMode                     string        `json:"pmf_mode"`
	Wpa3Transition              bool          `json:"wpa3_transition"`
	PassphraseAutogenerated     bool          `json:"passphrase_autogenerated"`
	PrivatePresharedKeys        []interface{} `json:"private_preshared_keys"`
	McastenhanceEnabled         bool          `json:"mcastenhance_enabled"`
	UsergroupId                 string        `json:"usergroup_id"`
	ProxyArp                    bool          `json:"proxy_arp"`
	UapsdEnabled                bool          `json:"uapsd_enabled"`
	IappEnabled                 bool          `json:"iapp_enabled"`
	RadiusprofileId             string        `json:"radiusprofile_id,omitempty"`
	Name                        string        `json:"name"`
	SiteId                      string        `json:"site_id"`
	HideSsid                    bool          `json:"hide_ssid"`
	WlanBand                    string        `json:"wlan_band"`
	Id                          string        `json:"_id"`
	PrivatePresharedKeysEnabled bool          `json:"private_preshared_keys_enabled"`
	No2GhzOui                   bool          `json:"no2ghz_oui"`
	XIappKey                    string        `json:"x_iapp_key"`
	NetworkconfId               string        `json:"networkconf_id"`
	DtimNa                      int           `json:"dtim_na"`
	IsGuest                     bool          `json:"is_guest"`
	MinrateNaEnabled            bool          `json:"minrate_na_enabled"`
	SaeGroups                   []interface{} `json:"sae_groups,omitempty"`
	Enabled                     bool          `json:"enabled"`
	SaePsk                      []interface{} `json:"sae_psk,omitempty"`
	WlanBands                   []string      `json:"wlan_bands"`
	MacFilterPolicy             string        `json:"mac_filter_policy"`
	Security                    string        `json:"security"`
	ApGroupIds                  []string      `json:"ap_group_ids"`
	L2Isolation                 bool          `json:"l2_isolation"`
	MinrateNgEnabled            bool          `json:"minrate_ng_enabled"`
	BssTransition               bool          `json:"bss_transition"`
	MinrateNgDataRateKbps       int           `json:"minrate_ng_data_rate_kbps"`
	RadiusMacAuthEnabled        bool          `json:"radius_mac_auth_enabled"`
	Wpa3FastRoaming             bool          `json:"wpa3_fast_roaming"`
	ScheduleWithDuration        []interface{} `json:"schedule_with_duration,omitempty"`
	ApGroupMode                 string        `json:"ap_group_mode"`
	Wpa3Enhanced192             bool          `json:"wpa3_enhanced_192"`
	FastRoamingEnabled          bool          `json:"fast_roaming_enabled"`
	WpaEnc                      string        `json:"wpa_enc"`
	XPassphrase                 string        `json:"x_passphrase,omitempty"`
	MacFilterList               []interface{} `json:"mac_filter_list"`
	DtimMode                    string        `json:"dtim_mode"`
	Schedule                    []interface{} `json:"schedule,omitempty"`
	BcFilterList                []interface{} `json:"bc_filter_list,omitempty"`
	MinrateNaDataRateKbps       int           `json:"minrate_na_data_rate_kbps"`
	MacFilterEnabled            bool          `json:"mac_filter_enabled"`
	DtimNg                      int           `json:"dtim_ng"`
}
